### PR TITLE
feat: add samarium 0.5.0 and 0.5.1

### PR DESCRIPTION
**Pull request by trag1c**

### CODE REVIEW

**Review by Enderchief — CHANGES_REQUESTED** [review]
```py
Traceback (most recent call last):
      File "/piston/packages/samarium/0.5.1/lib/python3.10/runpy.py", line 187, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/piston/packages/samarium/0.5.1/lib/python3.10/runpy.py", line 146, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/piston/packages/samarium/0.5.1/lib/python3.10/runpy.py", line 110, in _get_module_details
        __import__(pkg_name)
      File "/piston/packages/samarium/0.5.1/lib/python3.10/site-packages/samarium/__init__.py", line 7, in <module>
        from .shell import run_shell
      File "/piston/packages/samarium/0.5.1/lib/python3.10/site-packages/samarium/shell.py", line 5, in <module>
        import readline
    ImportError: libreadline.so.7: cannot open shared object file: No such file or directory
    
Exit Code: 1
```

there is an error

**Comment by trag1c** [comment]
> ```python
> Traceback (most recent call last):
>       File "/piston/packages/samarium/0.5.1/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>         mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>       File "/piston/packages/samarium/0.5.1/lib/python3.10/runpy.py", line 146, in _get_module_details
>         return _get_module_details(pkg_main_name, error)
>       File "/piston/packages/samarium/0.5.1/lib/python3.10/runpy.py", line 110, in _get_module_details
>         __import__(pkg_name)
>       File "/piston/packages/samarium/0.5.1/lib/python3.10/site-packages/samarium/__init__.py", line 7, in <module>
>         from .shell import run_shell
>       File "/piston/packages/samarium/0.5.1/lib/python3.10/site-packages/samarium/shell.py", line 5, in <module>
>         import readline
>     ImportError: libreadline.so.7: cannot open shared object file: No such file or directory
>     
> Exit Code: 1
> ```    
>   
> there is an error

I'm aware but I don't see how it's being triggered. This code was barely changed since 0.4.0 (and yet 0.4.0 works fine on io?):
```diff
-import readline
+from sys import platform
+
+if platform not in ("win32", "cygwin"):
+    import readline
```

**Comment by trag1c** [comment]
@Endercheif I found this: [System / pip readline versions mismatch](https://stackoverflow.com/questions/54483074/system-pip-readline-versions-mismatch) 🤔

**Comment by Enderchief** [comment]
LGTM :+1:

**Pull request merged**
